# Python

In [23]:
A = list(range(0,10))
B = 1,2,3



# Numpy


In [4]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array



x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [34]:
a = np.arange(10)**3

for i in a:
    print(i**(1/3.))


0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [41]:
A = np.array([0,0,3,4,5])

np.where( (A != 0) )

(array([2, 3, 4]),)

## ndim

Anzahl der achsen (dimensionen)

In [9]:
x3.ndim

3

## shape 

* 3 matritzen mit 4 zeilen mit 5 elementen

In [5]:
x3.shape

(3, 4, 5)

## size

* Anzahl der atomaren Elemente

In [10]:
x3.size

60

# dtype
* Typ der atomaren Elemente

In [11]:
x3.dtype

dtype('int64')

array([1, 2, 3, 4])